[rospy.client][INFO] 2019-06-02 15:06:26,360: init_node, name[/styx_server], pid[15003]
[xmlrpc][INFO] 2019-06-02 15:06:26,362: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-06-02 15:06:26,368: Started XML-RPC server [http://a917bedbf8a8:35263/]
[rospy.init][INFO] 2019-06-02 15:06:26,371: ROS Slave URI: [http://a917bedbf8a8:35263/]
[rospy.impl.masterslave][INFO] 2019-06-02 15:06:26,371: _ready: http://a917bedbf8a8:35263/
[xmlrpc][INFO] 2019-06-02 15:06:26,374: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2019-06-02 15:06:26,375: Registering with master node http://localhost:11311
[rospy.init][INFO] 2019-06-02 15:06:26,473: registered with master
[rospy.rosout][INFO] 2019-06-02 15:06:26,473: initializing /rosout core topic
[rospy.rosout][INFO] 2019-06-02 15:06:26,480: connected to core topic /rosout
[rospy.simtime][INFO] 2019-06-02 15:06:26,482: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2019-06-02 15:06:26,553: topic[/vehicle/brake_cmd] adding connection to [http://a917bedbf8a8:34479/], count 0
[rospy.internal][INFO] 2019-06-02 15:06:26,575: topic[/vehicle/throttle_cmd] adding connection to [http://a917bedbf8a8:34479/], count 0
[rospy.internal][INFO] 2019-06-02 15:06:26,583: topic[/vehicle/steering_cmd] adding connection to [http://a917bedbf8a8:34479/], count 0
[rospy.internal][INFO] 2019-06-02 15:06:26,685: topic[/vehicle/dbw_enabled] adding connection to [/dbw_node], count 0
[rospy.internal][INFO] 2019-06-02 15:06:26,686: topic[/current_velocity] adding connection to [/dbw_node], count 0
[rospy.internal][INFO] 2019-06-02 15:06:26,745: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2019-06-02 15:06:26,851: topic[/current_velocity] adding connection to [/pure_pursuit], count 1
[rospy.internal][INFO] 2019-06-02 15:06:26,852: topic[/current_pose] adding connection to [/pure_pursuit], count 0
[rospy.internal][INFO] 2019-06-02 15:06:27,795: topic[/current_pose] adding connection to [/waypoint_updater], count 1
[rospy.internal][INFO] 2019-06-02 15:06:27,890: topic[/final_waypoints] adding connection to [http://a917bedbf8a8:40269/], count 0
[rospy.internal][INFO] 2019-06-02 15:06:29,423: topic[/tf] adding connection to [/tl_detector], count 0
[rospy.internal][INFO] 2019-06-02 15:06:31,673: topic[/vehicle/traffic_lights] adding connection to [/tl_detector], count 0
[rospy.internal][INFO] 2019-06-02 15:06:31,684: topic[/image_color] adding connection to [/tl_detector], count 0
[rospy.internal][INFO] 2019-06-02 15:06:31,687: topic[/current_pose] adding connection to [/tl_detector], count 2
[rospy.core][INFO] 2019-06-02 15:07:54,880: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2019-06-02 15:07:54,882: Unable to initiate TCP/IP socket to a917bedbf8a8:35843 (http://a917bedbf8a8:40269/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2019-06-02 15:07:54,885: topic[/current_pose] adding connection to [/waypoint_updater], count 3
[rospy.internal][INFO] 2019-06-02 15:07:54,888: topic[/current_pose] removing connection to /waypoint_updater
[rospy.internal][ERROR] 2019-06-02 15:07:54,930: Unable to initiate TCP/IP socket to a917bedbf8a8:44061 (http://a917bedbf8a8:34479/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2019-06-02 15:07:54,932: Unable to initiate TCP/IP socket to a917bedbf8a8:44061 (http://a917bedbf8a8:34479/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2019-06-02 15:07:54,941: topic[/vehicle/dbw_enabled] removing connection to /dbw_node
[rospy.internal][INFO] 2019-06-02 15:07:54,942: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-06-02 15:07:54,943: topic[/current_velocity] removing connection to /dbw_node
[rospy.internal][INFO] 2019-06-02 15:07:54,944: topic[/current_velocity] removing connection to /pure_pursuit
[rospy.internal][WARNING] 2019-06-02 15:07:54,945: Unknown error initiating TCP/IP socket to a917bedbf8a8:44061 (http://a917bedbf8a8:34479/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 364, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2019-06-02 15:07:54,946: topic[/vehicle/brake_cmd] removing connection to http://a917bedbf8a8:34479/
[rospy.internal][INFO] 2019-06-02 15:07:54,946: topic[/tf] removing connection to /tl_detector
[rospy.internal][INFO] 2019-06-02 15:07:54,947: topic[/vehicle/traffic_lights] removing connection to /tl_detector
[rospy.internal][INFO] 2019-06-02 15:07:54,947: topic[/current_pose] removing connection to /pure_pursuit
[rospy.internal][INFO] 2019-06-02 15:07:54,948: topic[/current_pose] removing connection to /tl_detector
[rospy.internal][INFO] 2019-06-02 15:07:54,949: topic[/current_pose] removing connection to /waypoint_updater
[rospy.internal][INFO] 2019-06-02 15:07:54,949: topic[/image_color] removing connection to /tl_detector
[rospy.internal][INFO] 2019-06-02 15:07:54,949: topic[/vehicle/throttle_cmd] removing connection to http://a917bedbf8a8:34479/
[rospy.internal][INFO] 2019-06-02 15:07:54,950: topic[/final_waypoints] removing connection to http://a917bedbf8a8:40269/
[rospy.internal][INFO] 2019-06-02 15:07:54,950: topic[/vehicle/steering_cmd] removing connection to http://a917bedbf8a8:34479/
[rospy.impl.masterslave][INFO] 2019-06-02 15:07:54,950: signal-2
[rospy.core][INFO] 2019-06-02 15:08:01,615: signal_shutdown [atexit]
